os: WMF 5

skip_commits:
  message: /updated (readme|doc).*|update (readme|doc).*s/

install:
  - ps: Add-Content -Path ./DhcpServer.psm1 -Value 'function Get-DhcpServerInDC {}' -Encoding UTF8
  - ps: ipmo ./DhcpServer.psm1

build: false

test_script:
  - ps: .\build.ps1

deploy_script:
  - ps: Update-ModuleManifest -Path .\Get-DHCPScopePCStatus\Get-DHCPScopePCStatus.psd1 -ModuleVersion $env:APPVEYOR_BUILD_VERSION 

notifications:
- provider: Email
  to:
  - aartemjevas@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false